#!/bin/sh

# Ensure scripts have executable permission in case a checkout didn't
# preserve/set the file modes.  Only deal with the ones not acounted
# for by distinst, though these probably aren't all necessary.

xargs chmod +x <<EOF
./scripts/bootstrap.sh
./scripts/infotext_check_script_syntax.tcl
./scripts/mk_dist
./scripts/zerodepend
./scripts/scriptmessages.sh
./scripts/install.gettext
./scripts/distinst
./scripts/infotext_msg_parse.tcl
./scripts/format.sh
./scripts/compilearch
./scripts/gen_subtype_info.sh
./scripts/gelint
./scripts/link_jnilib.sh
./scripts/detab.sh
./scripts/ldAix
./scripts/mk_catman
./scripts/sge_log_tee
./scripts/analyze.rb
./scripts/removeGeneratedTags.pl
./scripts/mk_ascman
./scripts/nonreentrant.sh
./scripts/test_spooling_performance.sh
./scripts/make-tags.sh
./scripts/update-version-no
./dist/util/arch
./dist/util/setfileperm.sh
./dist/util/arch_variables
./dist/util/resources/drmaa4ruby/samples/test_all.sh
./3rdparty/qmake/config/install-sh
./3rdparty/qmake/config/mkinstalldirs
./3rdparty/qmake/configure
./3rdparty/qmake/config/missing
./3rdparty/qtcsh/install-sh
./3rdparty/qtcsh/configure
./3rdparty/qtcsh/config.sub
./3rdparty/qtcsh/config.guess
./clients/qmon/util/ad2c
./clients/qmon/util/create_de.sh
./clients/qmon/util/develToCVS
./clients/qmon/util/checkres
./clients/qmon/util/xmt_headers
./clients/qmon/util/clean_headers
./libs/juti/test_login.sh
./libs/juti/ca.sh
./libs/comm/test_certificate.csh
./libs/jgdi/xmldump
./libs/jgdi/jgdish
./libs/jgdi/run_test
./libs/jgdi/util/scripts/pe_task.sh
./libs/jgdi/util/scripts/pe_job.sh
./libs/jgdi/jobmon
./libs/jgdi/eventmon
./libs/jgdi/run_util.sh
./libs/jgdi/jgdievc
./aimk
../debian/rules
./configure
./scripts/pre-dist
EOF
