# Generated by Anaconda 34.25.0.29
# Generated by pykickstart v3.32
#version=RHEL9
cmdline
repo --name="Minimal" --baseurl=file:///run/install/ifelse(m4Rhel, `AlmaLinux9', `sources/mount-0000-cdrom', `repo')/Minimal

%addon com_redhat_kdump --enable --reserve-mb='auto'
%end

# Keyboard layouts
keyboard --xlayouts='us'
# System language
lang en_US.UTF-8
# Network information
network --bootproto=dhcp --device=ens3 --ipv6=auto --activate
network --hostname=localhost.localdomain
# Shutdown after installation
shutdown
# Use CDROM installation media
cdrom

%packages
@^minimal-environment
%end
# Run the Setup Agent on first boot
firstboot --disable
ignoredisk --only-use=sda
autopart
# Partition clearing information
clearpart --none --initlabel

%post --interpreter=/bin/bash --logfile=/root/ks-post.log
(
	set -eux
	sed -ie "s/SELINUX=enforcing/SELINUX=permissive/" /etc/selinux/config
	rm /etc/selinux/confige
	mkdir /root/.ssh
	chmod 700 /root/.ssh
	echo "m4SshPubKey" > /root/.ssh/authorized_keys
	echo sge-rhel9 > /etc/hostname
	dnf -y update
	dnf -y group install 'Development Tools'
	dnf -y install cmake hwloc-devel libdb-devel motif-devel ncurses-devel openssl-devel pam-devel rsync systemd-devel wget
	dnf -y install http://mirror.stream.centos.org/9-stream/CRB/x86_64/os/Packages/libtirpc-devel-1.3.2-1.el9.x86_64.rpm
	sed -ie "s/GRUB_TIMEOUT=5/GRUB_TIMEOUT=0/; s/ rhgb quiet//" /etc/default/grub
	rm /etc/default/grube
	grub2-mkconfig --output=/boot/grub2/grub.cfg
) 2>&1
%end

# System timezone
timezone America/Detroit --utc
# Root password
rootpw --plaintext SomeGridEngine # Change it in production!!!!!!!
